
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: Commander Miyoo
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: Commander binary
        path: output/DinguxCommander
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`